---
# tasks file for install_docker
- name: DOCKER |Установка пакетов
  apt:
    pkg: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: present
    update_cache: yes

- name: DOCKER |Получение GPG
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: DOCKER |Добавление репозитория docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    state: present

- name: DOCKER |Установка docker
  apt:
    pkg: ['docker-ce']
    state: present
    update_cache: yes

- name: DOCKER |Запуск сервиса docker
  service:
    name: docker
    state: started
    enabled: yes
  notify:
      - restart docker
