---
####################################
# Подготовка хостов
####################################
- name: ПОДГОТОВКА |Смена hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: ПОДГОТОВКА |Добавление доменов в hosts
  lineinfile: 
    path: /etc/hosts
    line: '"{{ ansible_host }}" "{{ inventory_hostname }}"'
  
- name: INSTALL |Установка пакетов
  apt:
    pkg: ['curl', 'apt-transport-https','git','iptables-persistent']
    state: present
    update_cache: yes
  
- name: ПОДГОТОВКА |Отключение SWAP
  shell: swapoff -a
  args:
    executable: /bin/bash

- name: ПОДГОТОВКА |Удаление Swap из fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: ПОДГОТОВКА |Добавление модулей ядра
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - br_netfilter
    - overlay

- name: ПОДГОТОВКА |Подключение модулей ядра
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: ПОДГОТОВКА |Добавление конфигурационного файла
  sysctl:
    name:  "{{ item }}"
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.bridge.bridge-nf-call-ip6tables
    - net.bridge.bridge-nf-call-iptables

- name: ПОДГОТОВКА |Установка docker
  import_tasks:  'install_docker.yml'

- name: ПОДГОТОВКА | Добавление /etc/docker/daemon.json
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker

- name: ПОДГОТОВКА |Импорт gpg key k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg.asc
    state: present
  become: true

- name: ПОДГОТОВКА |Добавление репозитория k8s
  lineinfile:
    path: /etc/apt/sources.list
    line: deb [trusted=yes] https://apt.kubernetes.io/ kubernetes-xenial main

- name: INSTALL |Установка компонентов k8s
  apt:
    pkg: ['kubelet','kubeadm','kubectl']
    state: present
    update_cache: yes

- name: ПОДГОТОВКА |Hold kubeadm
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: ПОДГОТОВКА |Установка 
  import_tasks:  'initializing_claster-master.yml'
  when: inventory_hostname == "k8s-master-1.adk.local"

- name: ПОДГОТОВКА |Установка 
  import_tasks:  'initializing_claster-workers.yml'
 # when: inventory_hostname | regex_search("^k8s-worker-(.*)$")


